version: "3.9"
services:
  ## mongodb database
  mongo:
    image: mongo
    container_name: mongodbTwilio
    networks:
      - devnetwork
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: password
    # volumes:
    #   - ./docker_files/mongo/mongodb_backup/:/data/db
    ports:
      - 27018:27017
    command: mongod --auth
    restart: always

  ## Mysql Server
  mysql:
    image: mysql:5.6
    networks:
      - devnetwork
    platform: linux/x86_64
    container_name: mysqldbTwilio
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: twilio
      MYSQL_USER: local
      MYSQL_PASSWORD: bgt54rfv
    #volumes:
    #  - ./docker_files/mysql/mysql_backup/:/docker-entrypoint-initdb.d
    # volumes:
    #   - ./docker_files/mysql/mysql_backup/:/home/
    ports:
      - 3308:3306
    networks:
      - devnetwork

networks:
  devnetwork: